In [430]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [431]:
data = pd.read_csv('CustomerData.csv', engine='python')

In [432]:
data.head()

,customerNo,firstName,middleName,lastName,email,phone,address,zipCode,city,state,...,PRIMARYCONTACTPHONEEXTENSION,RECEIPTOPTION,SALESTAXGROUP,TRANSFERSTATUS,Phone_ProcessIndicator,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,NaN,NaN,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
1,2,DolBnNeville,NaN,NaN,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
2,3,DolBnNeville,NaN,NaN,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
3,4,DolBnNeville,NaN,NaN,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
4,5,MicheXXeNariD,NaN,NaN,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN

In [433]:
#Data Exploration ...............................
# Columns
data.columns

Index(['customerNo', 'firstName', 'middleName', 'lastName', 'email', 'phone',
       'address', 'zipCode', 'city', 'state',
       ...
       'PRIMARYCONTACTPHONEEXTENSION', 'RECEIPTOPTION', 'SALESTAXGROUP',
       'TRANSFERSTATUS', 'Phone_ProcessIndicator', 'Address_ProcessIndicator',
       'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105'],
      dtype='object', length=106)

In [434]:
# unique values
data['firstName'].unique()

array(['MicheXXeNariD', 'DolBnNeville', 'SysonnRaNos', ...,
       'RudyBrdANRthhyst', 'StRphhBniRINani', 'MelissaLong'], dtype=object)

In [435]:
# Describe
data.describe()

,customerNo,middleName,maritalStatus,gender,languagePreference,partyCountry,partyState,guestCustomerInd,billingAddress,billingZipCode,...,PRIMARYCONTACTPHONEEXTENSION,RECEIPTOPTION,SALESTAXGROUP,TRANSFERSTATUS,Phone_ProcessIndicator,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
count,20000.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,19956.0,24.0,15.0,4.0,1.0
mean,10000.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,4.0,4.0
std,5773.647028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,4.0,4.0
25%,5000.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,4.0,4.0
50%,10000.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,4.0,4.0
75%,15000.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,4.0,4.0
max,20000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,4.0,4.0

In [436]:
# Duplicates
data[data[['email']].duplicated() == True].head()

,customerNo,firstName,middleName,lastName,email,phone,address,zipCode,city,state,...,PRIMARYCONTACTPHONEEXTENSION,RECEIPTOPTION,SALESTAXGROUP,TRANSFERSTATUS,Phone_ProcessIndicator,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
2,3,DolBnNeville,NaN,NaN,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
3,4,DolBnNeville,NaN,NaN,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
4,5,MicheXXeNariD,NaN,NaN,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
8,9,SysonnRaNos,NaN,NaN,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
9,10,SysonnRaNos,NaN,NaN,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN

In [437]:
data[data['middleName'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, middleName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, PARTYNUMBER, PRIMARYCONTACTEMAILDESCRIPTION, PRIMARYCONTACTFAX, PRIMARYCONTACTFAXPURPOSE, PRIMARYCONTACTFAXRECORDID, PRIMARYCONTACTPHONEEXTENSION, RECEIPTOPTION, SALESTAXGROUP, TRANSFERSTATUS, ...]
Index: []

[0 rows x 106 columns]

In [438]:
#Since all middle Names are NaN so we can delete that column
data = data.drop('middleName', axis=1)

In [439]:
data.head()

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,PRIMARYCONTACTPHONEEXTENSION,RECEIPTOPTION,SALESTAXGROUP,TRANSFERSTATUS,Phone_ProcessIndicator,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,NaN,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
1,2,DolBnNeville,NaN,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
2,3,DolBnNeville,NaN,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
3,4,DolBnNeville,NaN,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
4,5,MicheXXeNariD,NaN,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN

In [440]:
data['lastName'].fillna("Not Defined", inplace=True)

In [441]:
data.head()

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,PRIMARYCONTACTPHONEEXTENSION,RECEIPTOPTION,SALESTAXGROUP,TRANSFERSTATUS,Phone_ProcessIndicator,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN

In [442]:
data[data['PRIMARYCONTACTPHONEEXTENSION'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, PARTYNUMBER, PRIMARYCONTACTEMAILDESCRIPTION, PRIMARYCONTACTFAX, PRIMARYCONTACTFAXPURPOSE, PRIMARYCONTACTFAXRECORDID, PRIMARYCONTACTPHONEEXTENSION, RECEIPTOPTION, SALESTAXGROUP, TRANSFERSTATUS, Phone_ProcessIndicator, ...]
Index: []

[0 rows x 105 columns]

In [443]:
#Since all PRIMARYCONTACTPHONEEXTENSION are NaN so we can delete that column
data = data.drop('PRIMARYCONTACTPHONEEXTENSION', axis=1)

In [444]:
data[data['RECEIPTOPTION'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, PARTYNUMBER, PRIMARYCONTACTEMAILDESCRIPTION, PRIMARYCONTACTFAX, PRIMARYCONTACTFAXPURPOSE, PRIMARYCONTACTFAXRECORDID, RECEIPTOPTION, SALESTAXGROUP, TRANSFERSTATUS, Phone_ProcessIndicator, Address_ProcessIndicator, ...]
Index: []

[0 rows x 104 columns]

In [445]:
#Since all RECEIPTOPTION are NaN so we can delete that column
data = data.drop('RECEIPTOPTION', axis=1)

In [446]:
data.head()

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,PRIMARYCONTACTFAXPURPOSE,PRIMARYCONTACTFAXRECORDID,SALESTAXGROUP,TRANSFERSTATUS,Phone_ProcessIndicator,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN

In [447]:
data[data['PRIMARYCONTACTFAXPURPOSE'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, PARTYNUMBER, PRIMARYCONTACTEMAILDESCRIPTION, PRIMARYCONTACTFAX, PRIMARYCONTACTFAXPURPOSE, PRIMARYCONTACTFAXRECORDID, SALESTAXGROUP, TRANSFERSTATUS, Phone_ProcessIndicator, Address_ProcessIndicator, Unnamed: 102, ...]
Index: []

[0 rows x 103 columns]

In [448]:
data = data.drop('PRIMARYCONTACTFAXPURPOSE', axis=1)

In [449]:
data[data['SALESTAXGROUP'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, PARTYNUMBER, PRIMARYCONTACTEMAILDESCRIPTION, PRIMARYCONTACTFAX, PRIMARYCONTACTFAXRECORDID, SALESTAXGROUP, TRANSFERSTATUS, Phone_ProcessIndicator, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, ...]
Index: []

[0 rows x 102 columns]

In [450]:
data = data.drop('SALESTAXGROUP', axis=1)

In [451]:
data[data['TRANSFERSTATUS'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, PARTYNUMBER, PRIMARYCONTACTEMAILDESCRIPTION, PRIMARYCONTACTFAX, PRIMARYCONTACTFAXRECORDID, TRANSFERSTATUS, Phone_ProcessIndicator, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, ...]
Index: []

[0 rows x 101 columns]

In [452]:
data = data.drop('TRANSFERSTATUS', axis=1)

In [453]:
data[data['Phone_ProcessIndicator'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, PARTYNUMBER, PRIMARYCONTACTEMAILDESCRIPTION, PRIMARYCONTACTFAX, PRIMARYCONTACTFAXRECORDID, Phone_ProcessIndicator, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 100 columns]

In [454]:
data = data.drop('Phone_ProcessIndicator', axis=1)

In [455]:
data[data['Address_ProcessIndicator'].isnull()]

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,ITSCUSTTELEPHONECONTACTPREFID,PARTYNUMBER,PRIMARYCONTACTEMAILDESCRIPTION,PRIMARYCONTACTFAX,PRIMARYCONTACTFAXRECORDID,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
5,6,DolBnNeville,Not Defined,mlowe@dooney.com,9737692883,Unit 02,14th Floor,Kodak House II,155030,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
6,7,DolBnNeville,Not Defined,mattlowe04@gmail.com,9737692883,Unit 02,14th Floor,Kodak House,155030,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
7,8,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
8,9,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
9,10,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
10,11,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
11,12,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,Douglas So Unit 02,14th Floor,Kodak House II 39,196782,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
14,15,BrRttChanAra,Not Defined,brievans@hotmail.com,85296694001,Flat B,5th Floor,Chung Sahn House,NaN,196784,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
15,16,HonorBtoAejeDuD,Not Defined,nayial719@gmail.com,85297278115,1206,299 qrc,193180,Sheung Wan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
17,18,OctBviBDummerfielA,Not Defined,peter-beaugard@gmail.com,4848811578,345 W 145th St,11C1,196785,New York,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
19,20,JoRllRDunBan,Not Defined,Lauraderry@yahoo.co.uk,85290250607,10/A block 1,Victoria garden,NaN,196787,Hong kong,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
23,24,CBXvinNathh,Not Defined,Christinakw.lee@gmail.com,85297561015,18F,One International Financial Centre,NaN,196791,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
24,25,MicheXXeDimpDon,Not Defined,hsmcideal.ammenlam@gmail.com,85292526655,Flat H,28/F,Block 3,Grand Waterfront,196792,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
26,27,CaroXNaDiN,Not Defined,cclin-business@hotmail.com,85296520952,18/F.,GINZA SQUARE,565-567 NATHAN ROAD,196794,HONG KONG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
27,28,MRganJohnson,Not Defined,dfs@yahoo.com,85267987808,NaN,mlmk lkklkklk mmk,196795,hong,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
28,29,RebeGahhAiaz,Not Defined,azoneb11@hotmail.com,85297248086,12/F Fortis Tower,77-79 Gloucester Road,Wan Chai,196796,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
29,30,VRronicaBlack,Not Defined,myvictorialee@gmail.com,85291332886,Room 1717,China Merchants Tower,Shun Tak Centre,NaN,196797,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
32,33,CarXCXander,Not Defined,avischan@nifty.com,85228187730,UNIT 2703,69 JERVOIS STREET,NaN,196800,HONG KONG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
34,35,GRlliRGill,Not Defined,jenny22robinson@gmail.com,85292638755,Flat 20/B,Tower 1,Island Crest,8 First Street,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
598,599,cryceRaNirez,hhaNiltonCBrXos,debbiehodapp@hotmail.com,6192228084,4980 N. Harbor Drive,Suite 204,502109,San Diego,CA,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
695,696,CXarRNichaRl,WattDXBrissB,barnetdr@yahoo.com,6823161364,201 Main Street,Suite 304,197056,Fort Worth,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
805,806,BnnRAominguRz,FostRrDylan,bags731@yahoo.com,9126628611,24 Drayton Street,Suite 202,197093,Savannah,GA,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
1511,1512,CXBireMiBhael,RoArigyezCindy,russodebra50@gmail.com,2032065125,700 State Street,2nd Floor,197350,New Haven,CT,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
1979,1980,JoePerez,RamosRRbRkBh,damaso.garcia@gmail.com,3055935383,8400 NW 25th Street,NaN,197527,Doral,FL,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
2709,2710,GrBncineMBBlain,LopRzNBthBn,Fenigee@comcast.net,9254707970,10100 Trinity Parkway,Suite 105,578917,Stockton,CA,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
3497,3498,JBckFoDtRr,SynFrBnGlin,kimraye01@yahoo.com,2145379871,208 S. Akard st.,Room 1950.01,192591,Dallas,TX,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
3765,3766,PamRlaClaudia,KasRRmIdonB,rlavtcheva@gmail.com,6462626430,55 Water St,45th floor,column A12,A-1024,489745,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
3850,3851,BXGonsoJenDen,MBBlainPBscBXR,chatwithcarol@gmail.com,4252714593,6800 132nd PL SE,#E105,198172,Newcastle,WA,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
3928,3929,AXvinDepteNber,ThhompsonBlake,angiesboyst@hotmail.com,7032327101,2200 Pennsylvania Avenue,NW,198203,Washington,DC,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
3961,3962,DonovanSchwRiz,WolfIliana,EIWINN1@GMAIL.COM,3479018679,100-26,67th RD,198217,FOREST HILLS,NY,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
5028,5029,GByXRRPXillipD,DaiAnn,jwdodge@ameritech.net,2174150514,301 South Second Street,Room 112,198617,Springfield,IL,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
5556,5557,PBmelBBhapNan,NartinezJoshhuB,RAYMOND2705@AOL.COM,248,705,8791,760 BRIDGEPORT AVE APT 201,198784,STREETSBORO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
6887,6888,MerriXXDummerfielA,NielDenGraham,miraol27@gmail.com,7187127887,83-75 118 St.,Apt. 3E,199289,KEW Gardens,NY,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
7119,7120,BXyssBBolRNan,HRrNanJBnicR,carrieklugman@gmail.com,7812666855,200 Clarendon St,36th Floor,199372,Boston,MA,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
8266,8267,JaGeLi,KyNarAlisXa,KLobato26@aol.com,8315857235,49 San Miguel,suite 1,199760,Salinas,CA,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
10511,10512,JRnnifRrMitBhRll,VeAahhiXBry,PURPLESTILETTO@GMAIL.COM,2129694755,11 Times Sq.,Rm. 2521,171397,New York,NY,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
11472,11473,GRnnifRrhharriDon,BhhanAaKBrRRm,jlscpa55@juno.com,5132604559,Sheakley,Inc.,200847,Cincinnati,OH,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
12865,12866,RXijBhNitBhRll,GriffinGBcriRXXR,sheilahart18@comcast.net,2672593102,111 Presidential Blvd.,Suite 241,192669,Bala Cynwyd,PA,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
14517,14518,AidanRogerD,ButlRrSamuRl,atcollins74@live.com,NaN,Apt. 197,11111 N. Harrells Ferry Rd.,185759,BATON ROUGE,LA,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
14634,14635,GraceTXoNpson,DchhNiAtJoe,jeanedelen@gmail.com,NaN,2453 Corinth Ave,Apt G,374401,LOS ANGELES,CA,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
14765,14766,BshhlRyRoss,AnderDonSBmBnthB,bruce@bartholomewrealty.com,NaN,1560 Matthew Drive,Suite H,374003,FORT MYERS,FL,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN

In [456]:
data[data['Address_ProcessIndicator'].notnull()]

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,ITSCUSTTELEPHONECONTACTPREFID,PARTYNUMBER,PRIMARYCONTACTEMAILDESCRIPTION,PRIMARYCONTACTFAX,PRIMARYCONTACTFAXRECORDID,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
12,13,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,shangai,186821,Shanghai Municipal,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
13,14,TrBcyShR,Not Defined,fashionbaby317@gmail.com,85234567890,Jalan Radin,196783,sekinchan,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
16,17,HonorBtoAejeDuD,Not Defined,nayial719@gmail.com,85297278115,sheung wan,193180,Sheung Wan,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
18,19,KBtoBhhriDtophher,Not Defined,Websterlouise@yahoo.co.uk,85291339039,14b pearl gardens,196786,Hong kong,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
20,21,MeredithNunoz,Not Defined,Miradac@mac.com,8529539949,Flat A 10Floor,196788,Hong Kong,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
21,22,ClintonAoNingyRz,Not Defined,danielle.mcgrath@live.com,85293829665,Apartment 6G Wise Mansion,196789,Mid Levels,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
22,23,JiXXiBnMehta,Not Defined,cecislai@gmail.com,85269054204,Ã¦â€“Â°Ã§â€¢Å’Ã¥Â¤Â©Ã¦Â°Â´Ã¥Å“ï¿½Ã¥Â¤Â©Ã¨ï¿½Â¯Ã¦ï¿½â€˜Ã¨ï¿½Â¯Ã¨ï¿½Æ’Ã¦Â¨â€œ2402Ã¥Â®Â¤,196790,Hong Kong,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
25,26,KayKrane,Not Defined,lameyal@gmail.com,85266868757,Ã©Â¦â„¢Ã¦Â¸Â¯Ã¥Â°â€“Ã¦Â²â„¢Ã¥â€™â‚¬Ã¥Â¹Â¿Ã¤Â¸Å“Ã©ï¿½â€œ9Ã¥ï¿½Â·Ã¦Â¸Â¯Ã¥Â¨ï¿½Ã¥Â¤Â§Ã¥Å½Â¦Ã§Â¬Â¬6Ã¥ÂºÂ§,196793,hongkong,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
30,31,SysonnRaNos,Not Defined,test@test.com,3333333333,24 Ambrose Ln,196798,Northport,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
31,32,DonnBNath,Not Defined,Edzfegason@gmail.com,85297879504,1/f flat 1 block ab high west 142 pok fu lam road,196799,Hong kong,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
33,34,LBmBrBarrillo,Not Defined,marieleboutin14@gmail.com,68719384,106 fubon mansion tsat tsz mui road north point,196801,hong kong,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
35,36,ChhBrXRsNontgoNRry,AArianJBcGie,hasan.mustafa@systemsltd.com,NaN,11837 RIDGE PKWY APT 436,32892,BROOMFIELD,CO,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
36,37,PamRlaChhRrokRR,SRptRmbRrFrank,johnatsystems@gmail.com,NaN,1156 High St Stop 256,173369,SANTA CRUZ,CA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
37,38,IanKnox,ChhRrokRRDiRtRr,ksausker@aol.com,3037408982,7581 S ULSTER PL,196803,CENTENNIAL,CO,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
38,39,JoannaAomingyRz,DonynderDcoccy,Pinkpraiser@verizon.net,4102626420,842 REVERDY RD,196804,BALTIMORE,MD,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
39,40,DavisSummRrfiRld,InezCullen,ckdk1@verizon.net,9726584220,1808 FIELD COVE DR,164216,PLANO,TX,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
40,41,GylRBhhanAa,BeBkRBXpX,bratcherjoan@yahoo.com,2702879212,703 SPRING ST,61244,LEITCHFIELD,KY,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
41,42,NathaniRXKRlly,WarnerXisB,pwestdawn74@yahoo.com,7609878935,7736 CORSO ST,174070,RENO,NV,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
42,43,GiaraEspinoza,AoNinguRzMRghhan,jlbx2@verizon.net,8144742294,3756 FAIRCREST DR,498053,FAIRVIEW,PA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
43,44,AidanNielsen,DhRnMRXvin,eniolafada@yahoo.com,7579659691,4456 LEAMORE SQUARE RD,91248,VIRGINIA BEACH,VA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
44,45,BRnRdictBloDwiBk,XenAerDonEtXan,bkyoung@sc.rr.com,8037359473,812 LONGTOWN RD W,88854,BLYTHEWOOD,SC,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
45,46,KyleChanAa,PerezAllen,vinacpineda@comcast.net,7738071539,4600 N HARDING AVE,196805,CHICAGO,IL,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
46,47,EdyBrdoYoyng,NartinSBmyRX,emullin@qualitycoils.com,8605840927,51 COLMAN DR,196806,WOLCOTT,CT,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
47,48,GyleHector,UriRllRDuncBn,joannpink@yahoo.com,2102189903,1615 SANEZ,560280,SAN ANTONIO,TX,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
48,49,RyBnXayRD,XenAerDonEtXan,skykristine@yahoo.com,4258947590,5113 162ND PL SE,178381,BELLEVUE,WA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
49,50,BrianGrothh,GoelBpril,corkyandbonnie@msn.com,3036462823,5445 DTC PKWY STE 800,192254,GREENWOOD VILLAGE,CO,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
50,51,BarbaraADhhe,AejesushhirBm,renee4861@aol.com,4782328107,282 HAYES RD,49671,TENNILLE,GA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
51,52,EthanGibbs,DRntonSophhiB,triplef0628@msn.com,2124855987,72 HILLSIDE AVE,584782,HILLSIDE,NJ,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19970,19971,LaurRnJamRs,RaNirRzMaGayXa,marierendon@hotmail.com,3617272002,122 LING ST,204419,ROCKPORT,TX,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19971,19972,BquiXBTaDhya,EleanorSBmuel,bethgm@hotmail.com,5048882739,3000 TRANSCONTINENTAL DR,204420,METAIRIE,LA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19972,19973,KiaraTyler,LiangGBrRn,mlynnlyman@gmail.com,6033875595,975 KEARSARGE RD,155118,NORTH CONWAY,NH,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19973,19974,GBreemQuinteDDa,DiazcXBke,ivf515@hot.rr.com,NaN,707 Skyline Drive,374246,COPPERAS COVE,TX,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19974,19975,GBcriellBBox,KamalIXiana,lara_family@hotmail.com,3075753656,1942 E C ST,164421,TORRINGTON,WY,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19975,19976,MiGeRichard,BampBRllJyXiB,Nsborden@gmail.com,6015407597,130 AZALEA TRAILS DR,204421,BRANDON,MS,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19976,19977,crettPraDaA,GutierrezSheiXa,dheefner@gmail.com,7174047981,2028 LEAFMORE RD,461784,CHAMBERSBURG,PA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19977,19978,BlBnMerrill,DhharNaCBXRb,art-evans@hotmail.com,6625809802,507 E GRESHAM ST,40379,INDIANOLA,MS,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19978,19979,GiRrBnDRlgado,DanchhezAXexa,driverej@yahoo.com,7272724601,215 DUNLAP ST S APT 23,204422,SAINT PAUL,MN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19979,19980,ClBrRMontgomRry,KrausRTodd,dlewis@knights.ucf.edu,9544014611,3008 ANTIQUE OAKS CIR APT 106,204423,WINTER PARK,FL,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19980,19981,JoRMadan,RoDDBenjBmin,mrssanchez1228@gmail.com,6196653680,26504 PATRICIA LN,204424,HEMET,CA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19981,19982,GathhlRRnCarlson,AavisJosephh,haaguilar1@sbcglobal.net,4323522587,5110 GOLDER AVE,160295,ODESSA,TX,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19982,19983,GrBncineMBBlain,DyBraNDRBnnB,jennifergilbert@live.com,3528742854,11712 BUTTONHOOK DR,204425,CLERMONT,FL,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19983,19984,KBitXinRoArigyRz,EvanQuinn,Atl-lola007@hotmail.com,8053501265,1535 ACORN WAY APT A,204426,SOLVANG,CA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19984,19985,RlmoRobRrt,RzraXarissa,sarasidmore@gmail.com,5734897049,1 ALEXANDER ST APT 618,81094,YONKERS,NY,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19985,19986,Michhaelhholm,ArmandoDonovBn,murieb@comcast.net,3015471880,3104 CASSIDY ST,42884,WALDORF,MD,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19986,19987,GeXXiDhharNa,BhRrokRROtto,jcartiet@aol.com,9196565108,1502 CAIRO WAY,524890,FUQUAY VARINA,NC,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19987,19988,BonnieBhanAe,clancoRRginaXd,bwilson@olemiss.edu,6628010944,47 COUNTY ROAD 253,587799,ETTA,MS,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19988,19989,RudyBrdANRthhyst,BoAwinWintRr,shatoya429@msn.com,2817036169,2110 WITHAM PARK LN,403805,FRESNO,TX,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19989,19990,StRphhBniRINani,EvanQuinn,tedg145@gmail.com,(254) 3155095,12514 BRITE RNCH,204427,SAN ANTONIO,TX,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19990,19991,AvramKeithh,GolAsteincriBn,momiisean@gmail.com,4045749801,9243 FLOYD RD,204428,JONESBORO,GA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19991,19992,MelissaLong,SchweizMichelle,minasom@verizon.net,8179376047,1714 ROSEBRIAR LN,204429,KELLER,TX,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19992,19993,RRubRnDtuart,DominguRzWBltRr,slfleming69@yahoo.com,7087152518,1300 MILKWEED DR LIBERTY MEADOW ESTATES,204430,JOLIET,IL,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19993,19994,SandraZhheng,RaphhaRlBlRB,sherry_ricar@yahoo.com,8313321111,1111 ESTATES DR,204431,APTOS,CA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19994,19995,ChBncellorFulton,GaoGilbRrt,cindygross@aol.com,9182524248,4420 W LOUISVILLE ST,204432,BROKEN ARROW,OK,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19995,19996,MichheXXeDanchhez,BarrGrant,boydtarb@aol.com,9098964966,35323 STONECROP CT,204433,MURRIETA,CA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19996,19997,VictorBhriDtophRr,DiazNicole,Laadeebug3@aol.com,81494179664,408 BEAUMONT DR,465772,ALTOONA,PA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19997,19998,RichhBrdYarAley,WrigXtJordan,akaslim1@gmail.com,3018489544,11908 MARY CATHERINE DR,204434,CLINTON,MD,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19998,19999,StRvRHRrNan,RiBhardBurRliB,4robertsons@cox.net,5403098390,5623 WARWOOD DR,204435,ROANOKE,VA,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
19999,20000,IsoncRXXBNorgan,BoxGrBcR,kpchapman777@yahoo.com,9194898210,3516 MANFORD DR,75183,DURHAM,NC,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN

In [457]:
address_processIndicator = data['Address_ProcessIndicator'].mean()

In [458]:
#Replacing Nan with mean value for Address_ProcessIndicator
data['Address_ProcessIndicator'] = data['Address_ProcessIndicator'].replace(np.nan, address_processIndicator)

In [459]:
data.head()

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,ITSCUSTTELEPHONECONTACTPREFID,PARTYNUMBER,PRIMARYCONTACTEMAILDESCRIPTION,PRIMARYCONTACTFAX,PRIMARYCONTACTFAXRECORDID,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,NaN
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,NaN
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,NaN
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN

In [460]:
data[data['PRIMARYCONTACTFAXRECORDID'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, PARTYNUMBER, PRIMARYCONTACTEMAILDESCRIPTION, PRIMARYCONTACTFAX, PRIMARYCONTACTFAXRECORDID, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 99 columns]

In [461]:
data = data.drop('PRIMARYCONTACTFAXRECORDID', axis=1)

In [462]:
data[data['PRIMARYCONTACTFAX'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, PARTYNUMBER, PRIMARYCONTACTEMAILDESCRIPTION, PRIMARYCONTACTFAX, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 98 columns]

In [463]:
data = data.drop('PRIMARYCONTACTFAX', axis=1)

In [464]:
data[data['PRIMARYCONTACTEMAILDESCRIPTION'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, PARTYNUMBER, PRIMARYCONTACTEMAILDESCRIPTION, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 97 columns]

In [465]:
data = data.drop('PRIMARYCONTACTEMAILDESCRIPTION', axis=1)

In [466]:
data.head()

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,ITSCUSTDIRECTMAILCONTACTPREFID,ITSCUSTEMAILCONTACTPREFID,ITSCUSTRENTALCONTACTPREFID,ITSCUSTTELEPHONECONTACTPREFID,PARTYNUMBER,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,NaN
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,NaN
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,NaN
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN

In [467]:
data[data['PARTYNUMBER'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, PARTYNUMBER, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 96 columns]

In [468]:
data = data.drop('PARTYNUMBER', axis=1)

In [469]:
data[data['ITSCUSTTELEPHONECONTACTPREFID'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, ITSCUSTTELEPHONECONTACTPREFID, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 95 columns]

In [470]:
data = data.drop('ITSCUSTTELEPHONECONTACTPREFID', axis=1)

In [471]:
data[data['ITSCUSTRENTALCONTACTPREFID'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, ITSCUSTRENTALCONTACTPREFID, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 94 columns]

In [472]:
data = data.drop('ITSCUSTRENTALCONTACTPREFID', axis=1)

In [473]:
data[data['ITSCUSTEMAILCONTACTPREFID'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, ITSCUSTEMAILCONTACTPREFID, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 93 columns]

In [474]:
data = data.drop('ITSCUSTEMAILCONTACTPREFID', axis=1)

In [475]:
data[data['ITSCUSTDIRECTMAILCONTACTPREFID'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, ITSCUSTDIRECTMAILCONTACTPREFID, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 92 columns]

In [476]:
data = data.drop('ITSCUSTDIRECTMAILCONTACTPREFID', axis=1)

In [477]:
data.head()

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,DEFINITIONGROUP,DELIVERYMODE,EMPLOYEERESPONSIBLENUMBER,BILLINGADDRESSDESCRIPTION,ISSELECTED,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,NaN
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,NaN
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,NaN
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN

In [478]:
data[data['ISSELECTED'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, ISSELECTED, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 91 columns]

In [479]:
data = data.drop('ISSELECTED', axis=1)

In [480]:
data[data['BILLINGADDRESSDESCRIPTION'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, BILLINGADDRESSDESCRIPTION, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 90 columns]

In [481]:
data = data.drop('BILLINGADDRESSDESCRIPTION', axis=1)

In [482]:
data[data['EMPLOYEERESPONSIBLENUMBER'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, EMPLOYEERESPONSIBLENUMBER, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 89 columns]

In [483]:
data = data.drop('EMPLOYEERESPONSIBLENUMBER', axis=1)

In [484]:
data[data['DELIVERYMODE'].notnull()]

Empty DataFrame
Columns: [customerNo, firstName, lastName, email, phone, address, zipCode, city, state, country, county, addressValidFrom, addressValidTo, birthPlace, maritalStatus, gender, languagePreference, activeInd, companyType, organizationName, preferentialCustomer, partyType, partyCountry, partyState, guestCustomerInd, billingAddress, billingZipCode, billingCity, billingState, billingCountry, billingLatitude, billingLongitude, billingAddressValidFrom, billingAddressValidTo, shippingCity, shippingCountry, shippingState, shippingAddress, shippingAddressValidFrom, shippingAddressValidTo, shippingZipCode, primaryContactMobileInd, srcCreateDate, srcModifiedDate, syncStartDate, dax_DataAreaID, dax_CustomerGroupID, dax_currency, dax_isManuallyUnMerged, dax_UnMergedFromCustomerNo, isMDM, isMaster, isMerged, sourceSystem, loadDate, modifiedDate, GoldenCustomer, isManuallyMerged, DAX_ProcessInd, std_firstName, std_lastName, std_Address, IsValidZip, IsValidEmail, IsValidPhone, IsValidAddress, IsValidZipCode, IsValidCity, IsValidState, IsValidCountry, IsProcessed, SuggestedCity, SuggestedState, SuggestedCountry, FuzzyScore, MergeIndicator, ReceiptEmail, Delta_ProcessInd, std_email, std_phone, ADDRESSLOCATIONROLES, DEFINITIONGROUP, DELIVERYMODE, Address_ProcessIndicator, Unnamed: 102, Unnamed: 103, Unnamed: 104, Unnamed: 105]
Index: []

[0 rows x 88 columns]

In [485]:
data = data.drop('DELIVERYMODE', axis=1)

In [486]:
data[data['DEFINITIONGROUP'].notnull()]

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,Delta_ProcessInd,std_email,std_phone,ADDRESSLOCATIONROLES,DEFINITIONGROUP,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
34,35,GRlliRGill,Not Defined,jenny22robinson@gmail.com,85292638755,Flat 20/B,Tower 1,Island Crest,8 First Street,NaN,...,NaN,NaN,NaN,NaN,True,4.0,NaN,NaN,NaN,4.0

In [487]:
data['DEFINITIONGROUP'] = data['DEFINITIONGROUP'].replace(np.nan, False)

In [488]:
data.head()

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,Delta_ProcessInd,std_email,std_phone,ADDRESSLOCATIONROLES,DEFINITIONGROUP,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,NaN,True,NaN,NaN,False,4.0,4.0,NaN,NaN,NaN
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN

In [489]:
data[data['ADDRESSLOCATIONROLES'].isnull()]

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,Delta_ProcessInd,std_email,std_phone,ADDRESSLOCATIONROLES,DEFINITIONGROUP,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,NaN,True,NaN,NaN,False,4.0,4.0,NaN,NaN,NaN
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
5,6,DolBnNeville,Not Defined,mlowe@dooney.com,9737692883,Unit 02,14th Floor,Kodak House II,155030,Quarry Bay,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
6,7,DolBnNeville,Not Defined,mattlowe04@gmail.com,9737692883,Unit 02,14th Floor,Kodak House,155030,Quarry Bay,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
7,8,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
8,9,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
9,10,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
10,11,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
11,12,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,Douglas So Unit 02,14th Floor,Kodak House II 39,196782,Quarry Bay,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
12,13,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,shangai,186821,Shanghai Municipal,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
13,14,TrBcyShR,Not Defined,fashionbaby317@gmail.com,85234567890,Jalan Radin,196783,sekinchan,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
15,16,HonorBtoAejeDuD,Not Defined,nayial719@gmail.com,85297278115,1206,299 qrc,193180,Sheung Wan,NaN,...,NaN,True,NaN,NaN,False,4.0,4.0,NaN,NaN,NaN
16,17,HonorBtoAejeDuD,Not Defined,nayial719@gmail.com,85297278115,sheung wan,193180,Sheung Wan,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
17,18,OctBviBDummerfielA,Not Defined,peter-beaugard@gmail.com,4848811578,345 W 145th St,11C1,196785,New York,NaN,...,NaN,True,NaN,NaN,False,4.0,4.0,NaN,NaN,NaN
18,19,KBtoBhhriDtophher,Not Defined,Websterlouise@yahoo.co.uk,85291339039,14b pearl gardens,196786,Hong kong,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19,20,JoRllRDunBan,Not Defined,Lauraderry@yahoo.co.uk,85290250607,10/A block 1,Victoria garden,NaN,196787,Hong kong,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
20,21,MeredithNunoz,Not Defined,Miradac@mac.com,8529539949,Flat A 10Floor,196788,Hong Kong,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
21,22,ClintonAoNingyRz,Not Defined,danielle.mcgrath@live.com,85293829665,Apartment 6G Wise Mansion,196789,Mid Levels,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
22,23,JiXXiBnMehta,Not Defined,cecislai@gmail.com,85269054204,Ã¦â€“Â°Ã§â€¢Å’Ã¥Â¤Â©Ã¦Â°Â´Ã¥Å“ï¿½Ã¥Â¤Â©Ã¨ï¿½Â¯Ã¦ï¿½â€˜Ã¨ï¿½Â¯Ã¨ï¿½Æ’Ã¦Â¨â€œ2402Ã¥Â®Â¤,196790,Hong Kong,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
23,24,CBXvinNathh,Not Defined,Christinakw.lee@gmail.com,85297561015,18F,One International Financial Centre,NaN,196791,Hong Kong,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
25,26,KayKrane,Not Defined,lameyal@gmail.com,85266868757,Ã©Â¦â„¢Ã¦Â¸Â¯Ã¥Â°â€“Ã¦Â²â„¢Ã¥â€™â‚¬Ã¥Â¹Â¿Ã¤Â¸Å“Ã©ï¿½â€œ9Ã¥ï¿½Â·Ã¦Â¸Â¯Ã¥Â¨ï¿½Ã¥Â¤Â§Ã¥Å½Â¦Ã§Â¬Â¬6Ã¥ÂºÂ§,196793,hongkong,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
26,27,CaroXNaDiN,Not Defined,cclin-business@hotmail.com,85296520952,18/F.,GINZA SQUARE,565-567 NATHAN ROAD,196794,HONG KONG,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
27,28,MRganJohnson,Not Defined,dfs@yahoo.com,85267987808,NaN,mlmk lkklkklk mmk,196795,hong,NaN,...,NaN,True,NaN,NaN,False,4.0,4.0,NaN,NaN,NaN
28,29,RebeGahhAiaz,Not Defined,azoneb11@hotmail.com,85297248086,12/F Fortis Tower,77-79 Gloucester Road,Wan Chai,196796,Hong Kong,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
30,31,SysonnRaNos,Not Defined,test@test.com,3333333333,24 Ambrose Ln,196798,Northport,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
31,32,DonnBNath,Not Defined,Edzfegason@gmail.com,85297879504,1/f flat 1 block ab high west 142 pok fu lam road,196799,Hong kong,NaN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
32,33,CarXCXander,Not Defined,avischan@nifty.com,85228187730,UNIT 2703,69 JERVOIS STREET,NaN,196800,HONG KONG,...,NaN,NaN,True,NaN,False,4.0,NaN,4.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19970,19971,LaurRnJamRs,RaNirRzMaGayXa,marierendon@hotmail.com,3617272002,122 LING ST,204419,ROCKPORT,TX,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19971,19972,BquiXBTaDhya,EleanorSBmuel,bethgm@hotmail.com,5048882739,3000 TRANSCONTINENTAL DR,204420,METAIRIE,LA,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19972,19973,KiaraTyler,LiangGBrRn,mlynnlyman@gmail.com,6033875595,975 KEARSARGE RD,155118,NORTH CONWAY,NH,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19973,19974,GBreemQuinteDDa,DiazcXBke,ivf515@hot.rr.com,NaN,707 Skyline Drive,374246,COPPERAS COVE,TX,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19974,19975,GBcriellBBox,KamalIXiana,lara_family@hotmail.com,3075753656,1942 E C ST,164421,TORRINGTON,WY,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19975,19976,MiGeRichard,BampBRllJyXiB,Nsborden@gmail.com,6015407597,130 AZALEA TRAILS DR,204421,BRANDON,MS,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19976,19977,crettPraDaA,GutierrezSheiXa,dheefner@gmail.com,7174047981,2028 LEAFMORE RD,461784,CHAMBERSBURG,PA,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19977,19978,BlBnMerrill,DhharNaCBXRb,art-evans@hotmail.com,6625809802,507 E GRESHAM ST,40379,INDIANOLA,MS,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19978,19979,GiRrBnDRlgado,DanchhezAXexa,driverej@yahoo.com,7272724601,215 DUNLAP ST S APT 23,204422,SAINT PAUL,MN,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19979,19980,ClBrRMontgomRry,KrausRTodd,dlewis@knights.ucf.edu,9544014611,3008 ANTIQUE OAKS CIR APT 106,204423,WINTER PARK,FL,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19980,19981,JoRMadan,RoDDBenjBmin,mrssanchez1228@gmail.com,6196653680,26504 PATRICIA LN,204424,HEMET,CA,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19981,19982,GathhlRRnCarlson,AavisJosephh,haaguilar1@sbcglobal.net,4323522587,5110 GOLDER AVE,160295,ODESSA,TX,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19982,19983,GrBncineMBBlain,DyBraNDRBnnB,jennifergilbert@live.com,3528742854,11712 BUTTONHOOK DR,204425,CLERMONT,FL,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19983,19984,KBitXinRoArigyRz,EvanQuinn,Atl-lola007@hotmail.com,8053501265,1535 ACORN WAY APT A,204426,SOLVANG,CA,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19984,19985,RlmoRobRrt,RzraXarissa,sarasidmore@gmail.com,5734897049,1 ALEXANDER ST APT 618,81094,YONKERS,NY,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19985,19986,Michhaelhholm,ArmandoDonovBn,murieb@comcast.net,3015471880,3104 CASSIDY ST,42884,WALDORF,MD,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19986,19987,GeXXiDhharNa,BhRrokRROtto,jcartiet@aol.com,9196565108,1502 CAIRO WAY,524890,FUQUAY VARINA,NC,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19987,19988,BonnieBhanAe,clancoRRginaXd,bwilson@olemiss.edu,6628010944,47 COUNTY ROAD 253,587799,ETTA,MS,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19988,19989,RudyBrdANRthhyst,BoAwinWintRr,shatoya429@msn.com,2817036169,2110 WITHAM PARK LN,403805,FRESNO,TX,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19989,19990,StRphhBniRINani,EvanQuinn,tedg145@gmail.com,(254) 3155095,12514 BRITE RNCH,204427,SAN ANTONIO,TX,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19990,19991,AvramKeithh,GolAsteincriBn,momiisean@gmail.com,4045749801,9243 FLOYD RD,204428,JONESBORO,GA,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19991,19992,MelissaLong,SchweizMichelle,minasom@verizon.net,8179376047,1714 ROSEBRIAR LN,204429,KELLER,TX,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19992,19993,RRubRnDtuart,DominguRzWBltRr,slfleming69@yahoo.com,7087152518,1300 MILKWEED DR LIBERTY MEADOW ESTATES,204430,JOLIET,IL,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19993,19994,SandraZhheng,RaphhaRlBlRB,sherry_ricar@yahoo.com,8313321111,1111 ESTATES DR,204431,APTOS,CA,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19994,19995,ChBncellorFulton,GaoGilbRrt,cindygross@aol.com,9182524248,4420 W LOUISVILLE ST,204432,BROKEN ARROW,OK,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19995,19996,MichheXXeDanchhez,BarrGrant,boydtarb@aol.com,9098964966,35323 STONECROP CT,204433,MURRIETA,CA,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19996,19997,VictorBhriDtophRr,DiazNicole,Laadeebug3@aol.com,81494179664,408 BEAUMONT DR,465772,ALTOONA,PA,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19997,19998,RichhBrdYarAley,WrigXtJordan,akaslim1@gmail.com,3018489544,11908 MARY CATHERINE DR,204434,CLINTON,MD,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19998,19999,StRvRHRrNan,RiBhardBurRliB,4robertsons@cox.net,5403098390,5623 WARWOOD DR,204435,ROANOKE,VA,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN
19999,20000,IsoncRXXBNorgan,BoxGrBcR,kpchapman777@yahoo.com,9194898210,3516 MANFORD DR,75183,DURHAM,NC,USA,...,True,NaN,NaN,NaN,False,4.0,NaN,NaN,NaN,NaN

In [490]:
data['ADDRESSLOCATIONROLES'] = data['ADDRESSLOCATIONROLES'].replace(np.nan, False)

In [491]:
data['std_phone'] = data['std_phone'].replace(np.nan, False)

In [492]:
data['std_email'] = data['std_email'].replace(np.nan, False)

In [493]:
data['Delta_ProcessInd'] = data['Delta_ProcessInd'].replace(np.nan, False)

In [494]:
data.head()

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,Delta_ProcessInd,std_email,std_phone,ADDRESSLOCATIONROLES,DEFINITIONGROUP,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,True,False,False,False,False,4.0,NaN,NaN,NaN,NaN
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,False,True,False,False,False,4.0,4.0,NaN,NaN,NaN
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,False,False,True,False,False,4.0,NaN,4.0,NaN,NaN
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,False,False,True,False,False,4.0,NaN,4.0,NaN,NaN
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,NaN,USA,...,True,False,False,False,False,4.0,NaN,NaN,NaN,NaN

In [495]:
unnamed_102 = data['Unnamed: 102'].mean()

In [496]:
data['Unnamed: 102'] = data['Unnamed: 102'].replace(np.nan, unnamed_102)

In [497]:
unnamed_103 = data['Unnamed: 103'].mean()

In [498]:
data['Unnamed: 103'] = data['Unnamed: 103'].replace(np.nan, unnamed_103)

In [499]:
unnamed_104 = data['Unnamed: 104'].mean()

In [500]:
data['Unnamed: 104'] = data['Unnamed: 104'].replace(np.nan, unnamed_104)

In [501]:
unnamed_105 = data['Unnamed: 105'].mean()

In [502]:
data['Unnamed: 105'] = data['Unnamed: 105'].replace(np.nan, unnamed_105)

In [503]:
data['state'] = data['state'].replace(np.nan, 'Not Specified')

In [504]:
data.head()

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,Delta_ProcessInd,std_email,std_phone,ADDRESSLOCATIONROLES,DEFINITIONGROUP,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,True,False,False,False,False,4.0,4.0,4.0,4.0,4.0
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,False,True,False,False,False,4.0,4.0,4.0,4.0,4.0
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,False,False,True,False,False,4.0,4.0,4.0,4.0,4.0
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,False,False,True,False,False,4.0,4.0,4.0,4.0,4.0
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,Not Specified,USA,...,True,False,False,False,False,4.0,4.0,4.0,4.0,4.0

In [507]:
country_hot_encoding = pd.get_dummies(data['country'], prefix='country')

In [508]:
data.head()

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,Delta_ProcessInd,std_email,std_phone,ADDRESSLOCATIONROLES,DEFINITIONGROUP,Address_ProcessIndicator,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,True,False,False,False,False,4.0,4.0,4.0,4.0,4.0
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,False,True,False,False,False,4.0,4.0,4.0,4.0,4.0
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,False,False,True,False,False,4.0,4.0,4.0,4.0,4.0
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,False,False,True,False,False,4.0,4.0,4.0,4.0,4.0
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,Not Specified,USA,...,True,False,False,False,False,4.0,4.0,4.0,4.0,4.0

In [511]:
dataFrames = [data, country_hot_encoding]

In [516]:
merged_data = pd.concat(dataFrames, axis=1, sort=True)

In [518]:
merged_data.head()

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,country_MA,country_NY,country_OH,country_PA,country_Quarry Bay,country_STREETSBORO,country_Shanghai Municipal,country_TX,country_USA,country_WA
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,0,0,0,0,0,0,0,0,1,0
1,2,DolBnNeville,Not Defined,mkaur@Dooney.com,33333333333,Unit 02,14th Floor,193361,Central and Western,Hong Kong,...,0,0,0,0,0,0,0,0,0,0
2,3,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,0,0,0,0,1,0,0,0,0,0
3,4,DolBnNeville,Not Defined,a_zahidpk@hotmail.com,6099479471,Unit 02,14th Floor,Kodak House II 39 Healthy Str,178189,Quarry Bay,...,0,0,0,0,1,0,0,0,0,0
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0

In [520]:
#Filtering Data
merged_data[merged_data['country']=='USA']

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,country_MA,country_NY,country_OH,country_PA,country_Quarry Bay,country_STREETSBORO,country_Shanghai Municipal,country_TX,country_USA,country_WA
0,1,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,Central and Western,Hong Kong,USA,...,0,0,0,0,0,0,0,0,1,0
4,5,MicheXXeNariD,Not Defined,a_zahidpk@hotmail.com,6099479471,GORNIAK drive,154966,parlin,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
12,13,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,shangai,186821,Shanghai Municipal,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
13,14,TrBcyShR,Not Defined,fashionbaby317@gmail.com,85234567890,Jalan Radin,196783,sekinchan,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
16,17,HonorBtoAejeDuD,Not Defined,nayial719@gmail.com,85297278115,sheung wan,193180,Sheung Wan,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
18,19,KBtoBhhriDtophher,Not Defined,Websterlouise@yahoo.co.uk,85291339039,14b pearl gardens,196786,Hong kong,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
20,21,MeredithNunoz,Not Defined,Miradac@mac.com,8529539949,Flat A 10Floor,196788,Hong Kong,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
21,22,ClintonAoNingyRz,Not Defined,danielle.mcgrath@live.com,85293829665,Apartment 6G Wise Mansion,196789,Mid Levels,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
22,23,JiXXiBnMehta,Not Defined,cecislai@gmail.com,85269054204,Ã¦â€“Â°Ã§â€¢Å’Ã¥Â¤Â©Ã¦Â°Â´Ã¥Å“ï¿½Ã¥Â¤Â©Ã¨ï¿½Â¯Ã¦ï¿½â€˜Ã¨ï¿½Â¯Ã¨ï¿½Æ’Ã¦Â¨â€œ2402Ã¥Â®Â¤,196790,Hong Kong,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
25,26,KayKrane,Not Defined,lameyal@gmail.com,85266868757,Ã©Â¦â„¢Ã¦Â¸Â¯Ã¥Â°â€“Ã¦Â²â„¢Ã¥â€™â‚¬Ã¥Â¹Â¿Ã¤Â¸Å“Ã©ï¿½â€œ9Ã¥ï¿½Â·Ã¦Â¸Â¯Ã¥Â¨ï¿½Ã¥Â¤Â§Ã¥Å½Â¦Ã§Â¬Â¬6Ã¥ÂºÂ§,196793,hongkong,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
30,31,SysonnRaNos,Not Defined,test@test.com,3333333333,24 Ambrose Ln,196798,Northport,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
31,32,DonnBNath,Not Defined,Edzfegason@gmail.com,85297879504,1/f flat 1 block ab high west 142 pok fu lam road,196799,Hong kong,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
33,34,LBmBrBarrillo,Not Defined,marieleboutin14@gmail.com,68719384,106 fubon mansion tsat tsz mui road north point,196801,hong kong,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0
35,36,ChhBrXRsNontgoNRry,AArianJBcGie,hasan.mustafa@systemsltd.com,NaN,11837 RIDGE PKWY APT 436,32892,BROOMFIELD,CO,USA,...,0,0,0,0,0,0,0,0,1,0
36,37,PamRlaChhRrokRR,SRptRmbRrFrank,johnatsystems@gmail.com,NaN,1156 High St Stop 256,173369,SANTA CRUZ,CA,USA,...,0,0,0,0,0,0,0,0,1,0
37,38,IanKnox,ChhRrokRRDiRtRr,ksausker@aol.com,3037408982,7581 S ULSTER PL,196803,CENTENNIAL,CO,USA,...,0,0,0,0,0,0,0,0,1,0
38,39,JoannaAomingyRz,DonynderDcoccy,Pinkpraiser@verizon.net,4102626420,842 REVERDY RD,196804,BALTIMORE,MD,USA,...,0,0,0,0,0,0,0,0,1,0
39,40,DavisSummRrfiRld,InezCullen,ckdk1@verizon.net,9726584220,1808 FIELD COVE DR,164216,PLANO,TX,USA,...,0,0,0,0,0,0,0,0,1,0
40,41,GylRBhhanAa,BeBkRBXpX,bratcherjoan@yahoo.com,2702879212,703 SPRING ST,61244,LEITCHFIELD,KY,USA,...,0,0,0,0,0,0,0,0,1,0
41,42,NathaniRXKRlly,WarnerXisB,pwestdawn74@yahoo.com,7609878935,7736 CORSO ST,174070,RENO,NV,USA,...,0,0,0,0,0,0,0,0,1,0
42,43,GiaraEspinoza,AoNinguRzMRghhan,jlbx2@verizon.net,8144742294,3756 FAIRCREST DR,498053,FAIRVIEW,PA,USA,...,0,0,0,0,0,0,0,0,1,0
43,44,AidanNielsen,DhRnMRXvin,eniolafada@yahoo.com,7579659691,4456 LEAMORE SQUARE RD,91248,VIRGINIA BEACH,VA,USA,...,0,0,0,0,0,0,0,0,1,0
44,45,BRnRdictBloDwiBk,XenAerDonEtXan,bkyoung@sc.rr.com,8037359473,812 LONGTOWN RD W,88854,BLYTHEWOOD,SC,USA,...,0,0,0,0,0,0,0,0,1,0
45,46,KyleChanAa,PerezAllen,vinacpineda@comcast.net,7738071539,4600 N HARDING AVE,196805,CHICAGO,IL,USA,...,0,0,0,0,0,0,0,0,1,0
46,47,EdyBrdoYoyng,NartinSBmyRX,emullin@qualitycoils.com,8605840927,51 COLMAN DR,196806,WOLCOTT,CT,USA,...,0,0,0,0,0,0,0,0,1,0
47,48,GyleHector,UriRllRDuncBn,joannpink@yahoo.com,2102189903,1615 SANEZ,560280,SAN ANTONIO,TX,USA,...,0,0,0,0,0,0,0,0,1,0
48,49,RyBnXayRD,XenAerDonEtXan,skykristine@yahoo.com,4258947590,5113 162ND PL SE,178381,BELLEVUE,WA,USA,...,0,0,0,0,0,0,0,0,1,0
49,50,BrianGrothh,GoelBpril,corkyandbonnie@msn.com,3036462823,5445 DTC PKWY STE 800,192254,GREENWOOD VILLAGE,CO,USA,...,0,0,0,0,0,0,0,0,1,0
50,51,BarbaraADhhe,AejesushhirBm,renee4861@aol.com,4782328107,282 HAYES RD,49671,TENNILLE,GA,USA,...,0,0,0,0,0,0,0,0,1,0
51,52,EthanGibbs,DRntonSophhiB,triplef0628@msn.com,2124855987,72 HILLSIDE AVE,584782,HILLSIDE,NJ,USA,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19970,19971,LaurRnJamRs,RaNirRzMaGayXa,marierendon@hotmail.com,3617272002,122 LING ST,204419,ROCKPORT,TX,USA,...,0,0,0,0,0,0,0,0,1,0
19971,19972,BquiXBTaDhya,EleanorSBmuel,bethgm@hotmail.com,5048882739,3000 TRANSCONTINENTAL DR,204420,METAIRIE,LA,USA,...,0,0,0,0,0,0,0,0,1,0
19972,19973,KiaraTyler,LiangGBrRn,mlynnlyman@gmail.com,6033875595,975 KEARSARGE RD,155118,NORTH CONWAY,NH,USA,...,0,0,0,0,0,0,0,0,1,0
19973,19974,GBreemQuinteDDa,DiazcXBke,ivf515@hot.rr.com,NaN,707 Skyline Drive,374246,COPPERAS COVE,TX,USA,...,0,0,0,0,0,0,0,0,1,0
19974,19975,GBcriellBBox,KamalIXiana,lara_family@hotmail.com,3075753656,1942 E C ST,164421,TORRINGTON,WY,USA,...,0,0,0,0,0,0,0,0,1,0
19975,19976,MiGeRichard,BampBRllJyXiB,Nsborden@gmail.com,6015407597,130 AZALEA TRAILS DR,204421,BRANDON,MS,USA,...,0,0,0,0,0,0,0,0,1,0
19976,19977,crettPraDaA,GutierrezSheiXa,dheefner@gmail.com,7174047981,2028 LEAFMORE RD,461784,CHAMBERSBURG,PA,USA,...,0,0,0,0,0,0,0,0,1,0
19977,19978,BlBnMerrill,DhharNaCBXRb,art-evans@hotmail.com,6625809802,507 E GRESHAM ST,40379,INDIANOLA,MS,USA,...,0,0,0,0,0,0,0,0,1,0
19978,19979,GiRrBnDRlgado,DanchhezAXexa,driverej@yahoo.com,7272724601,215 DUNLAP ST S APT 23,204422,SAINT PAUL,MN,USA,...,0,0,0,0,0,0,0,0,1,0
19979,19980,ClBrRMontgomRry,KrausRTodd,dlewis@knights.ucf.edu,9544014611,3008 ANTIQUE OAKS CIR APT 106,204423,WINTER PARK,FL,USA,...,0,0,0,0,0,0,0,0,1,0
19980,19981,JoRMadan,RoDDBenjBmin,mrssanchez1228@gmail.com,6196653680,26504 PATRICIA LN,204424,HEMET,CA,USA,...,0,0,0,0,0,0,0,0,1,0
19981,19982,GathhlRRnCarlson,AavisJosephh,haaguilar1@sbcglobal.net,4323522587,5110 GOLDER AVE,160295,ODESSA,TX,USA,...,0,0,0,0,0,0,0,0,1,0
19982,19983,GrBncineMBBlain,DyBraNDRBnnB,jennifergilbert@live.com,3528742854,11712 BUTTONHOOK DR,204425,CLERMONT,FL,USA,...,0,0,0,0,0,0,0,0,1,0
19983,19984,KBitXinRoArigyRz,EvanQuinn,Atl-lola007@hotmail.com,8053501265,1535 ACORN WAY APT A,204426,SOLVANG,CA,USA,...,0,0,0,0,0,0,0,0,1,0
19984,19985,RlmoRobRrt,RzraXarissa,sarasidmore@gmail.com,5734897049,1 ALEXANDER ST APT 618,81094,YONKERS,NY,USA,...,0,0,0,0,0,0,0,0,1,0
19985,19986,Michhaelhholm,ArmandoDonovBn,murieb@comcast.net,3015471880,3104 CASSIDY ST,42884,WALDORF,MD,USA,...,0,0,0,0,0,0,0,0,1,0
19986,19987,GeXXiDhharNa,BhRrokRROtto,jcartiet@aol.com,9196565108,1502 CAIRO WAY,524890,FUQUAY VARINA,NC,USA,...,0,0,0,0,0,0,0,0,1,0
19987,19988,BonnieBhanAe,clancoRRginaXd,bwilson@olemiss.edu,6628010944,47 COUNTY ROAD 253,587799,ETTA,MS,USA,...,0,0,0,0,0,0,0,0,1,0
19988,19989,RudyBrdANRthhyst,BoAwinWintRr,shatoya429@msn.com,2817036169,2110 WITHAM PARK LN,403805,FRESNO,TX,USA,...,0,0,0,0,0,0,0,0,1,0
19989,19990,StRphhBniRINani,EvanQuinn,tedg145@gmail.com,(254) 3155095,12514 BRITE RNCH,204427,SAN ANTONIO,TX,USA,...,0,0,0,0,0,0,0,0,1,0
19990,19991,AvramKeithh,GolAsteincriBn,momiisean@gmail.com,4045749801,9243 FLOYD RD,204428,JONESBORO,GA,USA,...,0,0,0,0,0,0,0,0,1,0
19991,19992,MelissaLong,SchweizMichelle,minasom@verizon.net,8179376047,1714 ROSEBRIAR LN,204429,KELLER,TX,USA,...,0,0,0,0,0,0,0,0,1,0
19992,19993,RRubRnDtuart,DominguRzWBltRr,slfleming69@yahoo.com,7087152518,1300 MILKWEED DR LIBERTY MEADOW ESTATES,204430,JOLIET,IL,USA,...,0,0,0,0,0,0,0,0,1,0
19993,19994,SandraZhheng,RaphhaRlBlRB,sherry_ricar@yahoo.com,8313321111,1111 ESTATES DR,204431,APTOS,CA,USA,...,0,0,0,0,0,0,0,0,1,0
19994,19995,ChBncellorFulton,GaoGilbRrt,cindygross@aol.com,9182524248,4420 W LOUISVILLE ST,204432,BROKEN ARROW,OK,USA,...,0,0,0,0,0,0,0,0,1,0
19995,19996,MichheXXeDanchhez,BarrGrant,boydtarb@aol.com,9098964966,35323 STONECROP CT,204433,MURRIETA,CA,USA,...,0,0,0,0,0,0,0,0,1,0
19996,19997,VictorBhriDtophRr,DiazNicole,Laadeebug3@aol.com,81494179664,408 BEAUMONT DR,465772,ALTOONA,PA,USA,...,0,0,0,0,0,0,0,0,1,0
19997,19998,RichhBrdYarAley,WrigXtJordan,akaslim1@gmail.com,3018489544,11908 MARY CATHERINE DR,204434,CLINTON,MD,USA,...,0,0,0,0,0,0,0,0,1,0
19998,19999,StRvRHRrNan,RiBhardBurRliB,4robertsons@cox.net,5403098390,5623 WARWOOD DR,204435,ROANOKE,VA,USA,...,0,0,0,0,0,0,0,0,1,0
19999,20000,IsoncRXXBNorgan,BoxGrBcR,kpchapman777@yahoo.com,9194898210,3516 MANFORD DR,75183,DURHAM,NC,USA,...,0,0,0,0,0,0,0,0,1,0

In [524]:
merged_data[merged_data['email'].isnull()]

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,country_MA,country_NY,country_OH,country_PA,country_Quarry Bay,country_STREETSBORO,country_Shanghai Municipal,country_TX,country_USA,country_WA
3449,3450,AllisonhhRrnanARz,WalkerJoshuB,NaN,6122024889,19479 LOWELL ST NW,38282,ELK RIVER,MN,USA,...,0,0,0,0,0,0,0,0,1,0
11627,11628,cryceRaNirez,TorrRDIsaiahh,NaN,NaN,C/O YANKEE STADIUM,374347,BRONX,NY,USA,...,0,0,0,0,0,0,0,0,1,0
15995,15996,TonyaVRga,BevisAlvin,NaN,NaN,5615 Poston Way Apt #121,374033,KNOXVILLE,TN,USA,...,0,0,0,0,0,0,0,0,1,0
16259,16260,WangSchhweiz,Nevillehhasad,NaN,2198283191,5280e 1350n,202802,San Pierre,IN,USA,...,0,0,0,0,0,0,0,0,1,0

In [526]:
merged_data['email'] = merged_data['email'].replace(np.nan, 'Not Specified')

In [530]:
#Filtered Systemers
systems = merged_data[merged_data['email'].str.contains('systemsltd')]

In [531]:
#Filtered Visionet Employees
visionetsystems = merged_data[merged_data['email'].str.contains('visionetsystems')]

In [532]:
#Merging data
systems_visionet = pd.concat([systems, visionetsystems])

In [533]:
systems_visionet

,customerNo,firstName,lastName,email,phone,address,zipCode,city,state,country,...,country_MA,country_NY,country_OH,country_PA,country_Quarry Bay,country_STREETSBORO,country_Shanghai Municipal,country_TX,country_USA,country_WA
35,36,ChhBrXRsNontgoNRry,AArianJBcGie,hasan.mustafa@systemsltd.com,NaN,11837 RIDGE PKWY APT 436,32892,BROOMFIELD,CO,USA,...,0,0,0,0,0,0,0,0,1,0
7,8,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,0,0,0,0,0,0,1,0,0,0
8,9,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,0,0,0,0,0,0,1,0,0,0
9,10,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,0,0,0,0,0,0,1,0,0,0
10,11,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,Room 5183,51F Raffles City Centre,No.268 Xi Zang,65345,Shanghai Municipal,...,0,0,0,0,0,0,1,0,0,0
12,13,SysonnRaNos,Not Defined,khurram.saleem@visionetsystems.com,2123127618,shangai,186821,Shanghai Municipal,Not Specified,USA,...,0,0,0,0,0,0,0,0,1,0